'use strict';
const $ = id => document.getElementById(id);
const state = {csrf:'',data:null,tab:'overview',stream:null,bootstrap:false};
const labels={pending:'等待登记',active:'启用',draining:'停止分配',disabled:'已停用',revoked:'已撤销',running:'运行中',stopped:'未启动',succeeded:'成功',failed:'失败',expired:'已过期',superseded:'已被新配置替代'};
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function button(text,fn,cls){const b=el('button',text,cls);b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){notice(e.message,true);}finally{b.disabled=false;}};return b;}
function date(v){if(!v||Date.parse(v)<1000)return '—';return new Date(v).toLocaleString('zh-CN',{hour12:false});}
function notice(text,error=false){const target=$('modal').open?$('modal-message'):$('message');target.replaceChildren(el('div',text,error?'error':'success'));}
function badge(text,kind){return el('span',text,'badge '+(kind||''));}
function json(v){return el('pre',JSON.stringify(v,null,2));}
function uid(){return Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');}
async function api(path,body,method){const m=method||(body===undefined?'GET':'POST');const headers={'Content-Type':'application/json'};if(m!=='GET'){headers['X-CSRF-Token']=state.csrf;headers['Idempotency-Key']=uid();}const r=await fetch('/v2/admin'+path,{method:m,headers,body:body===undefined?undefined:JSON.stringify(body)});let out;try{out=await r.json();}catch{throw new Error('控制端响应无法读取，请检查反代和服务日志。');}if(!r.ok){if(r.status===401&&path!=='/login'){signedOut();}throw new Error(({unauthorized:'账号或密码错误，或会话已失效，请重新登录。',forbidden:'操作未获授权，请检查临时密钥是否过期或已使用。',conflict:'状态已变化，请刷新页面后重试；旧接入密钥需要重新签发。',rate_limited:'操作过于频繁，请一分钟后重试。',invalid_request:'提交内容无效，请检查名称、端口和必填项。'})[out.code]||out.message||'操作失败');}return out;}
function modal(title){$('modal-title').textContent=title;$('modal-body').replaceChildren();$('modal-message').replaceChildren();if(!$('modal').open)$('modal').showModal();return $('modal-body');}
$('modal-close').onclick=()=>$('modal').close();
$('modal').onclose=()=>{$('modal-body').replaceChildren();$('modal-message').replaceChildren();};
function signedOut(){state.csrf='';state.stream?.close();state.stream=null;state.data=null;$('content').replaceChildren();$('modal').close();$('modal-body').replaceChildren();$('app').hidden=true;$('auth').hidden=false;}
async function signedIn(session){state.csrf=session.csrf;$('auth').hidden=true;$('app').hidden=false;await refresh();state.stream?.close();const stream=new EventSource('/v2/admin/events');state.stream=stream;stream.addEventListener('snapshot',e=>{state.data=JSON.parse(e.data);$('connection').textContent='控制端已连接';render();});stream.onerror=()=>{$('connection').textContent='连接中断，正在重试';api('/session').catch(()=>{});};}
async function refresh(){state.data=await api('/snapshot');render();}
$('auth-switch').onclick=()=>{state.bootstrap=!state.bootstrap;$('bootstrap-field').hidden=!state.bootstrap;$('auth-title').textContent=state.bootstrap?'初始化管理员':'欢迎回来';$('auth-copy').textContent=state.bootstrap?'先在控制服务器运行 nodelane-server admin bootstrap。':'登录后管理节点、房间和网络授权。';$('login-submit').textContent=state.bootstrap?'创建管理员':'登录管理台';$('auth-switch').textContent=state.bootstrap?'返回登录':'首次部署？初始化管理员';$('auth-error').textContent='';};
$('login-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const b=$('login-submit');b.disabled=true;$('auth-error').textContent='';try{const data=Object.fromEntries(new FormData(form));if(state.bootstrap){await api('/bootstrap',data);$('auth-switch').click();$('auth-error').textContent='管理员已创建，请登录。';}else{await signedIn(await api('/login',data));}form.password.value='';form.code.value='';}catch(e){$('auth-error').textContent=e.message;}finally{b.disabled=false;}};
$('logout').onclick=async()=>{try{await api('/logout',{});}finally{signedOut();}};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('selected',x===b));render(true);});
function table(heads,rows){const wrap=el('div',undefined,'table-wrap');const t=el('table'),head=el('tr');heads.forEach(h=>head.append(el('th',h)));const thead=el('thead');thead.append(head);t.append(thead);const body=el('tbody');rows.forEach(cells=>{const tr=el('tr');cells.forEach(c=>{const td=el('td');td.append(c instanceof Node?c:document.createTextNode(String(c??'—')));tr.append(td);});body.append(tr);});t.append(body);wrap.append(t);if(!rows.length)wrap.append(el('p','暂无记录','empty'));return wrap;}
function card(title){const c=el('div',undefined,'card');if(title)c.append(el('h2',title));return c;}
function connected(n){return Date.parse(n.last_seen)>Date.now()-45000;}
function external(n){const samples=[];for(const source of state.data.nodes){if(!['active','draining'].includes(source.state)||!connected(source))continue;for(const p of source.report?.probes||[]){if(p.device_id===n.device_id&&p.address===n.address&&Date.parse(p.at)>Date.now()-60000)samples.push({...p,source:source.name});}}return samples;}
function reach(n){const ps=external(n);if(!ps.length)return badge('尚未验证','warn');const direct=ps.find(p=>p.mode==='direct-public'&&p.rtt_ms!=null);if(direct)return badge('UDP 已验证','good');if(ps.some(p=>['direct','relay','direct-public'].includes(p.mode)&&p.rtt_ms!=null))return badge('隧道可达，入口待验证','warn');return badge('探测路径失败','bad');}
function nodeRows(nodes){return nodes.map(n=>{const name=el('div',n.name);name.append(el('small',n.region+' · '+n.address));const actions=el('div');actions.append(button('详情',()=>nodeDetail(n)),button('配置',()=>editNode(n)));return [name,badge(labels[n.state]||n.state),badge(connected(n)?'已连接':'未连接',connected(n)?'good':'warn'),badge(labels[n.report?.engine]||'等待启动',n.report?.engine==='running'?'good':'warn'),reach(n),n.report?.error?'失败 / 待处理':n.report?.applied_revision===n.revision?'已生效':!connected(n)?'已保存，等待接收':'应用中 v'+n.revision,actions];});}
function render(force=false){const d=state.data;if(!d)return;$('clock').textContent='更新于 '+date(d.server_time);const titles={overview:'总览',nodes:'节点',rooms:'房间',system:'系统',events:'操作记录'};$('page-title').textContent=titles[state.tab];const root=$('content');if(!force&&state.tab==='system'&&root.querySelector('form'))return;root.replaceChildren();
 if(state.tab==='overview'){
  const grid=el('div',undefined,'grid');for(const [title,value,copy] of [['运行中的节点',d.nodes.filter(n=>connected(n)&&n.report?.engine==='running'&&n.state==='active').length,'控制连接与本机引擎正常'],['需要处理的节点',d.nodes.filter(n=>!['revoked','disabled'].includes(n.state)&&(!connected(n)||n.report?.engine!=='running'||n.report?.error)).length,'查看具体失败步骤与建议'],['活跃房间',d.rooms.filter(r=>!r.closed&&Date.parse(r.expires_at)>Date.now()).length,'每房最多 32 人 · 默认 24 小时']]){const c=card();c.append(el('span',title,'muted'),el('div',value,'metric'),el('small',copy));grid.append(c);}root.append(grid);const days=Math.floor((Date.parse(d.ca_expires_at)-Date.now())/86400000);if(days<=30)root.append(el('div','Nebula CA 将在 '+days+' 天后到期，请安排维护。节点短期证书续签不会延长 CA 有效期。','notice'));const c=card('节点运行状态');c.append(table(['节点 / 入口','分配策略','控制连接','本机引擎','外部连通','配置','操作'],nodeRows(d.nodes)));root.append(c);
 }else if(state.tab==='nodes'){
  const bar=el('div',undefined,'toolbar');bar.append(el('h2','网络节点'),button('添加节点',()=>editNode(), 'primary'));root.append(bar);const c=card();c.append(table(['节点 / 入口','分配策略','控制连接','本机引擎','外部连通','配置','操作'],nodeRows(d.nodes)));root.append(c);
 }else if(state.tab==='rooms'){
  const c=card();c.append(table(['房间','游戏','状态','到期时间','操作'],d.rooms.map(r=>[r.name,r.game,badge(r.closed?'已关闭':Date.parse(r.expires_at)>Date.now()?'开放中':'已过期'),date(r.expires_at),button('查看成员',()=>roomDetail(r))])));root.append(c);
 }else if(state.tab==='events'){
  const c=card('节点操作结果');c.append(table(['动作','节点','状态','创建时间','错误'],d.operations.map(o=>[o.action,d.nodes.find(n=>n.id===o.node_id)?.name||o.node_id,badge(labels[o.state]||o.state,o.state==='failed'?'bad':''),date(o.created_at),o.error||'—'])));root.append(c);const audit=card('审计记录');audit.append(table(['时间','操作者','事件','目标','内容'],d.events.map(e=>[date(e.created_at),e.actor,e.kind,e.target,button('查看',()=>modal('事件详情').append(json(e)))])));root.append(audit);
 }else{
  const c=card('部署信息');c.append(details({'产品版本':d.version,'部署身份':d.deployment_id,'游戏地址池':d.network,'Nebula CA 到期':date(d.ca_expires_at),'HTTPS 证书':'由现有反向代理管理','数据库':'当前快照已从 PostgreSQL 读取'}));c.append(el('p','CA 到期前需安排维护。本版提供提前提醒；短期证书自动续签。','notice'));root.append(c);const p=card('修改管理员密码');const f=el('form');field(f,'current','当前密码','','password');field(f,'password','新密码（12–128 字节）','','password');const b=el('button','保存新密码','primary');b.type='submit';f.append(b);f.onsubmit=async e=>{e.preventDefault();b.disabled=true;try{await api('/password',Object.fromEntries(new FormData(f)));signedOut();$('auth-error').textContent='密码已修改，请重新登录。';}catch(e){notice(e.message,true);}finally{b.disabled=false;}};p.append(f);root.append(p);
 }
}
function details(obj){const list=el('dl',undefined,'detail-list');Object.entries(obj).forEach(([k,v])=>list.append(el('dt',k),el('dd',String(v??'—'))));return list;}
function field(form,name,label,value='',type='text'){const l=el('label',label),i=el(type==='textarea'?'textarea':'input');i.name=name;if(type!=='textarea')i.type=type;i.value=value;i.required=!['notes'].includes(name);if(type==='password')i.autocomplete='off';l.append(i);form.append(l);return i;}
function editNode(n){const body=modal(n?'修改节点配置':'添加节点'),f=el('form');field(f,'name','节点名称',n?.name||'');field(f,'region','区域',n?.region||'default');field(f,'address','公网域名或 IP（可附端口，默认 UDP 4242）',n?.address||'').placeholder='node.example.com 或 203.0.113.10:4242';field(f,'notes','备注',n?.notes||'','textarea');for(const [name,label] of [['lighthouse','地址发现（lighthouse）'],['relay','中继（relay）']]){const l=el('label'),i=el('input');i.type='checkbox';i.name=name;i.checked=n?n[name]:true;l.append(i,document.createTextNode(label));f.append(l);}const b=el('button',n?'保存配置':'创建节点','primary');b.type='submit';f.append(b);if(n)body.append(el('p','修改 UDP 端口后，需要同步应用本机监听或 Compose 端口映射。已有连接可能短暂重连。','notice'));body.append(f);f.onsubmit=async e=>{e.preventDefault();b.disabled=true;try{const c=Object.fromEntries(new FormData(f));c.address=c.address.trim();if(!c.address.includes(':')||(c.address.startsWith('[')&&c.address.endsWith(']')))c.address+=':4242';c.lighthouse=f.lighthouse.checked;c.relay=f.relay.checked;const out=n?await api('/nodes/'+n.id,{config:c,revision:n.revision},'PUT'):await api('/nodes',c);await refresh();nodeDetail(out);notice(n?'配置已保存，等待节点应用。':'节点已创建，可以生成临时接入密钥。');}catch(e){notice(e.message,true);}finally{b.disabled=false;}};}
function nodeDetail(original){const n=state.data.nodes.find(x=>x.id===original.id)||original;const body=modal(n.name);body.append(details({'节点编号':n.id,'机器身份':n.device_id||'等待登记','身份代次':n.generation,'公网入口':n.address,'虚拟 IP':n.ip||'—','最近心跳':date(n.last_seen),'程序版本':n.report?.version||'—','配置版本':(n.report?.applied_revision||0)+' / '+n.revision,'最近续签':date(n.report?.last_renewal),'证书到期':date(n.report?.lease_expires_at),'运行错误':n.report?.error||'无'}));const actions=el('div',undefined,'actions');
 if(n.state==='pending')actions.append(button('生成临时接入密钥',()=>issueKey(n),'primary'));
 const available={active:[['drain','停止分配'],['disable','停用'],['restart','重启网络']],draining:[['resume','恢复分配'],['disable','停用'],['restart','重启网络']],disabled:[['resume','恢复节点']],pending:[['revoke-key','撤销接入密钥']]};
 for(const [action,label] of available[n.state]||[])actions.append(button(label,()=>nodeAction(n,action,label)));
 if(n.device_id&&n.state!=='revoked')actions.append(button('替换服务器',()=>nodeAction(n,'replace','替换服务器'),'danger'));
 if(n.state!=='revoked')actions.append(button('永久撤销',()=>nodeAction(n,'revoke','永久撤销'),'danger'));
 actions.append(button('下载 Compose YAML',()=>{const a=el('a');a.href='/v2/admin/nodes/'+n.id+'/compose';a.download='compose.node.yaml';a.click();}));body.append(actions);body.append(el('h3','外部探测'));const samples=external(n);body.append(samples.length?table(['来源','路径','RTT','时间'],samples.map(p=>[p.source,p.mode,p.rtt_ms==null?'失败':p.rtt_ms.toFixed(1)+' ms',date(p.at)])):el('p','尚未收到外部探测。控制连接成功不代表公网 UDP 入口已验证。','muted'));body.append(button('刷新详情',async()=>{await refresh();nodeDetail(n);}));}
async function nodeAction(n,action,label){const body=modal(label+'：'+n.name);const copy={drain:'停止加入新连接候选，保留身份和续签；连接迁移可能短暂重连。',disable:'撤销当前数据面证书，保留管理连接以便恢复。',replace:'撤销旧机器身份并隔离旧地址，新机器需要使用新的接入密钥登记。',revoke:'永久撤销该节点身份。在线设备将更新撤销状态；失联设备受当前证书截止时间约束。',restart:'重启 Nebula 数据面，已有连接将短暂中断。'};body.append(el('p',copy[action]||'将更新节点配置并等待节点确认。'));body.append(button('确认'+label,async()=>{await api('/nodes/'+n.id+'/actions',{action});await refresh();nodeDetail(n);notice('操作已保存，执行进度见操作记录。');},action==='revoke'?'danger':'primary'));}
async function issueKey(n){const out=await api('/nodes/'+n.id+'/key',{});const body=modal('接入 '+n.name);body.append(el('p','密钥仅本次展示，有效期 30 分钟，只能成功登记一台机器。关闭后需要重新生成。','notice'));const secret=el('pre',out.key,'key');body.append(secret,button('复制密钥',()=>navigator.clipboard.writeText(out.key)));body.append(el('h3','宿主机原生安装'));body.append(el('pre','curl -fsSL '+location.origin+'/install/node.sh | bash -s -- --server '+location.origin+' --network '+state.data.network));body.append(el('p','在 root 终端执行，随后粘贴密钥。Debian/Ubuntu systemd 主机适用。'));body.append(el('h3','Compose / 1Panel'));body.append(el('p','下载该节点 YAML 并启动容器，在容器终端执行：'),el('pre','nlroom-node enroll'));}
async function roomDetail(r){const s=await api('/rooms/'+r.id);const body=modal(r.name);body.append(details({'房间编号':r.id,'游戏':r.game,'到期时间':date(r.expires_at)}));body.append(table(['成员','虚拟 IP','最近心跳','操作'],s.members.map(m=>[m.name,m.ip,date(m.last_seen),button('踢出',()=>confirmRoom(r,'kick',m.device_id),'danger')])));body.append(el('h3','已登记端口'),table(['设备','协议','端口','到期时间'],s.endpoints.map(p=>[p.device_id,p.protocol,p.port,date(p.expires_at)])));if(!r.closed)body.append(button('关闭房间',()=>confirmRoom(r,'close',''),'danger'));}
function confirmRoom(r,action,device){const body=modal(action==='close'?'关闭房间':'踢出成员');body.append(el('p','此操作会撤销相关授权并关闭已有连接。'));body.append(button('确认执行',async()=>{await api('/rooms/'+r.id+'/actions',{action,device_id:device});$('modal').close();await refresh();notice('房间授权已更新。');},'danger'));}
api('/session').then(signedIn).catch(()=>{});
